-- MySQL Script generated by MySQL Workbench
-- Mon Jun 18 13:46:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mattenshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mattenshop` ;

-- -----------------------------------------------------
-- Schema mattenshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mattenshop` DEFAULT CHARACTER SET utf8 ;
USE `mattenshop` ;

-- -----------------------------------------------------
-- Table `mattenshop`.`klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mattenshop`.`klant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `voornaam` VARCHAR(50) NOT NULL,
  `achternaam` VARCHAR(50) NOT NULL,
  `tussenvoegsel` VARCHAR(15) NULL DEFAULT NULL,
  `sortering` INT NULL,
  `aktief` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_klant_email` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mattenshop`.`adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mattenshop`.`adres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `straatnaam` VARCHAR(50) NOT NULL,
  `huisnummer` INT NOT NULL,
  `toevoeging` VARCHAR(5) NULL DEFAULT NULL,
  `postcode` VARCHAR(6) NOT NULL,
  `woonplaats` VARCHAR(30) NOT NULL,
  `klant_id` INT NOT NULL,
  `adres_type` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adres_klant_idx` (`klant_id` ASC),
  CONSTRAINT `fk_adres_klant`
    FOREIGN KEY (`klant_id`)
    REFERENCES `mattenshop`.`klant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mattenshop`.`bestelling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mattenshop`.`bestelling` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `klant_id` INT NOT NULL,
  `totaalprijs` DECIMAL(6,2) NOT NULL,
  `besteldatum` DATE NOT NULL,
  `bestelstatus` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bestelling_klant1_idx` (`klant_id` ASC),
  CONSTRAINT `fk_bestelling_klant1`
    FOREIGN KEY (`klant_id`)
    REFERENCES `mattenshop`.`klant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mattenshop`.`artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mattenshop`.`artikel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `prijs` DECIMAL(6,2) NOT NULL,
  `voorraad` INT NOT NULL,
  `gereserveerd` INT NOT NULL,
  `sortering` INT NULL,
  `aktief` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `naam_UNIQUE` (`naam` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mattenshop`.`bestel_regel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mattenshop`.`bestel_regel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bestelling_id` INT NOT NULL,
  `artikel_id` INT NOT NULL,
  `aantal` INT NOT NULL,
  `prijs` DECIMAL(6,2) NOT NULL,
  INDEX `fk_bestelling_has_artikel_artikel1_idx` (`artikel_id` ASC),
  INDEX `fk_bestelling_has_artikel_bestelling1_idx` (`bestelling_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_bestelling_artikel` (`bestelling_id` ASC, `artikel_id` ASC),
  CONSTRAINT `fk_bestelling_has_artikel_bestelling1`
    FOREIGN KEY (`bestelling_id`)
    REFERENCES `mattenshop`.`bestelling` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bestelling_has_artikel_artikel1`
    FOREIGN KEY (`artikel_id`)
    REFERENCES `mattenshop`.`artikel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mattenshop`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mattenshop`.`account` (
  `email` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(180) NOT NULL,
  `account_type` CHAR(1) NOT NULL,
  `klant_id` INT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_account_klant1_idx` (`klant_id` ASC),
  CONSTRAINT `fk_account_klant1`
    FOREIGN KEY (`klant_id`)
    REFERENCES `mattenshop`.`klant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
